# Generated by Django 4.1.7 on 2023-09-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('property_cost', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=255)),
                ('property_area', models.CharField(max_length=255)),
                ('property_locality', models.CharField(max_length=255)),
                ('property_city', models.CharField(max_length=255)),
                ('individual_property_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('records_scraped', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=20)),
                ('schedule', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
